### ISSUE TITLE
Category: "Live Action" is misspelled as "Live Ation"

### ISSUE THREAD

**Issue by NeilSeligmann** [ChrisAlderson/nyaa-api-pt#1]
The error is at the file:
> nyaa-api-pt.js: line 50

```
live_ation: {
    category_id: '5_0',
    sub_categories: {
        (...)
    }
},
```

and also in the documentation of the readme file.

**Comment by ChrisAlderson** [comment]
Should be fixed in aa5ce34b3bd626644f631e80d071b9f50a6608b7, thanks for the issue.
